sudo: required
language: scala
cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt/boot/
    - $HOME/.cache/pip
jdk:
  - oraclejdk8

services:
  - docker

script:
  - sbt test "set dockerUpdateLatest := true" 'set packageName in Docker := "play-container"' docker:publishLocal

after_success:
  - if [ "$TRAVIS_BRANCH" == "master" ]; then ./publish-image.sh; fi
