sudo: required
language: scala
cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt/boot/
    - geoip-resources
jdk:
  - oraclejdk8

services:
  - docker

script:
  - sbt test docker:publishLocal

after_success:
  - if [ "$TRAVIS_BRANCH" == "master" ]; then
      if  [ -n "$AWS_ACCESS_KEY_ID" ] && \
          [ -n "$AWS_SECRET_ACCESS_KEY" ] && \
          [ -n "$AWS_ACCOUNT_ID" ] && \
          [ -n "$AWS_REGION" ] && \
          [ -n "$AWS_DOCKER_REPOSITORY" ]; then
        pip install --user awscli
        export PATH=$PATH:$HOME/.local/bin
        eval $(aws ecr get-login --region $AWS_REGION)
        docker tag play-docker-example "$AWS_ACCOUNT_ID".dkr.ecr."$AWS_REGION".amazonaws.com/"$AWS_DOCKER_REPOSITORY"
        docker push "$AWS_ACCOUNT_ID".dkr.ecr."$AWS_REGION".amazonaws.com/"$AWS_DOCKER_REPOSITORY"
      else
        echo "Not publishing to AWS ECR due to missing requirements."
      fi
      if [ -n "$DOCKER_USERNAME" ] && [ -n "$DOCKER_PASSWORD" ] && [ -n "$DOCKER_REPOSITORY" ]; then
        docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
        docker push "$DOCKER_REPOSITORY";
      else
        echo "Not publishing Docker Hub due to missing environment variables."
      fi
    fi
